与 Java 的异常处理机制相比，Kotlin 抛弃了 checked 异常，相当于所有异常都是 runtime
异常，这意味着开发者想捕获异常就捕获，不想捕获异常也行，不需要使用 throws 关键字声明抛出异常 

## 9.1.1 使用 try...catch 捕获异常

```text
try {
    //业务实现代码
} catch (e: Exception) {
    //异常处理代码
}finally {
    //可选的 finally 块
}
```

- 包含 1 个try 块、 0～N个 catch 块、 0～l 个 finally 块，但 catch 块与 finally 块至少出现其中之一
```kotlin

import java.io.*
fun main(args: Array<String>) {
    var fis: FileInputStream? = null
    try {
        fis = FileInputStream("a.txt")
    } catch (ioe: IOException) {
        println(ioe.message)
        // return语句强制方法返回 执行finally
        return       // ①
        // 使用exit退出虚拟机
//         System.exit(1)     // ②  不执行finally
    } finally {
        // 关闭磁盘文件，回收资源
        fis?.close()
        println("执行finally块里的资源回收!")
    }
}
```

- 一旦在 finally 块中使用了 return 或 throw 语句，就将会导致 try 块、 catch 块中的 return、 throw 语句失效

```kotlin
//FinallyFlowTest.kt
fun main(args: Array<String>) {
    var a = test()
    println(a)//false
}
fun test(): Boolean {
    try {
        // 因为finally块中包含了return语句
        // 所以下面的return语句失去作用
        return true
    } finally {
        return false
    }
}
```

`如果 finally 块中也使用了 re阳m 或 throw 等导致 方法中止的语句， finally 块己经中止了方法，
系统将不会跳回去执行 try 块 、 catch 块中的任何
 代码。`
 
 ## 9.1.2 异常类的继承体系
 Kotlin 提供了 kotlin.Throwable 类，所有的异常类都是 Throwable 类的子类
 
 ```kotlin
 
fun main(args: Array<String>) {
    try{
        var a = Integer.parseInt(args[0])
        var b = Integer.parseInt(args[1])
        val c = a / b
        println("您输入的两个数相除的结果是：${c}")
    } catch (ie: IndexOutOfBoundsException) {
        println("数组越界：运行程序时输入的参数个数不够")
    } catch (ne: NumberFormatException) {
        println("数字格式异常：程序只能接收整数参数")
    } catch (ae: ArithmeticException) {
        println("算术异常")
    } catch (e: Exception) {
        println("未知异常")
    }
}
```

## 9.1.3 访问异常信息

所有的异常对象都包含了如下几个常用属性和方法。
- message ： 该属性返回该异常的详细描述字符串。
- stackTrace ： 该属性返回该异常的跟踪枝信息。
- printStackTrace()： 将该异常的跟踪枝信息输出到标准错误输出。
- printStackTrace(PrintStream s）： 将该异常的跟踪枝信息输出到指定输出流。

```kotlin
import java.io.*
fun main(args: Array<String>) {
    try{
        var fis = FileInputStream("a.txt")
    } catch (ioe: IOException) {
        println(ioe.message)
        ioe.printStackTrace()
    }
}
```

## 9.1.4 try 语句是表达式

与 if 语句类似， Kotlin 的try语句也是表达式，因此位try吾句也可用于对变量赋值 。 try 表
达式的返回值是try块中的最后一个表达式的值，或者是被执行的 catch 块中的最后一个表达
式的值， finally 块中的内容不会影响表达式的结果

```kotlin

fun main(args: Array<String>) {
    val input = readLine()
    // 用try表达式对变量a赋值
    val a: Int? = try {Integer.parseInt(input) } catch (e: NumberFormatException) { null }
    println(a)
}
```

